import type { SupabaseClient } from '@supabase/supabase-js'

/**
 * اسم الدخول — الافتراضي: الرقم الوظيفي (employee_number)
 * مع إمكانية تعديل يدوي لمدير النظام والحسابات الخارجية
 */

export function normalizeLoginUsername(raw: string): string {
  return raw.trim()
}

export function suggestUsernameFromEmployeeNumber(
  employeeNumber?: string | number | null,
): string | null {
  if (employeeNumber == null || employeeNumber === '') return null
  const value = normalizeLoginUsername(String(employeeNumber))
  return value || null
}

export type FieldValidation =
  | { ok: true; value: string }
  | { ok: false; error: string }

export function validateLoginUsername(raw: string): FieldValidation {
  const value = normalizeLoginUsername(raw)
  if (!value) {
    return { ok: false, error: 'أدخل رقم الموظف أو اسم المستخدم' }
  }
  if (value.length < 3) {
    return { ok: false, error: 'اسم الدخول قصير جداً (3 أحرف على الأقل)' }
  }
  if (value.length > 40) {
    return { ok: false, error: 'اسم الدخول طويل جداً (40 حرفاً كحد أقصى)' }
  }
  if (!/^[\w.\-@+]+$/i.test(value)) {
    return { ok: false, error: 'استخدم أحرفاً إنجليزية وأرقاماً و . - _ @ + فقط (بدون مسافات)' }
  }
  return { ok: true, value }
}

export type PasswordValidation = { ok: true } | { ok: false; error: string }

/** كلمة مرور قوية — 8+ أحرف، حرف ورقم */
export function validateLoginPassword(raw: string): PasswordValidation {
  if (!raw || raw.length < 8) {
    return { ok: false, error: 'كلمة المرور 8 أحرف على الأقل' }
  }
  if (!/[a-zA-Z\u0600-\u06FF]/.test(raw)) {
    return { ok: false, error: 'كلمة المرور تحتاج حرفاً واحداً على الأقل' }
  }
  if (!/[0-9]/.test(raw)) {
    return { ok: false, error: 'كلمة المرور تحتاج رقماً واحداً على الأقل' }
  }
  return { ok: true }
}

export function isAutoGeneratedUsername(username?: string | null): boolean {
  if (!username) return false
  return /^emp_\d+$/.test(username)
}

export function shouldSuggestUsernameFromHr(
  currentUsername?: string | null,
  usernameManuallyEdited?: boolean,
): boolean {
  if (usernameManuallyEdited) return false
  if (!currentUsername?.trim()) return true
  return isAutoGeneratedUsername(currentUsername)
}

export async function checkUsernameAvailable(
  supabase: SupabaseClient,
  tenantId: string,
  username: string,
  excludeEmployeeId?: number,
): Promise<{ available: boolean; error?: string }> {
  const { data, error } = await supabase
    .from('employees')
    .select('id')
    .eq('tenant_id', tenantId)
    .ilike('username', username)
    .limit(1)

  if (error) return { available: false, error: error.message }
  if (!data?.length) return { available: true }
  if (excludeEmployeeId && data[0].id === excludeEmployeeId) return { available: true }
  return { available: false }
}

export const LOGIN_USERNAME_LABEL = 'رقم الموظف أو اسم المستخدم'
export const LOGIN_USERNAME_PLACEHOLDER = 'مثال: 10042'
